# Enricher!
#
# This is a function, it filters data based on gene clusters, genes, and pathways!
# It returns an enrichment chart for the filtered data.
#
#' Pathway Enrichment Filtering and Plotting
#'
#' This function filters a dataset based on provided cluster #'s, genes, or pathways and generates an enrichment chart.
#'
#' @description This function allows you to filter a dataset of pathway enrichment data by specific clusters, genes, or pathways and visualize the resulting enrichment using a plot.
#'
#' @param data Clustered results from pathfindR experiment using pathfindR cluster_enriched_terms(data, plot_dend = TRUE, plot_clusters_graph = TRUE)
#' @param clusters A numeric vector of cluster IDs to filter the data. Default is NULL.
#' @param genes A vector of gene names to filter the data. Default is NULL.
#' @param pathways A vector of pathway names to filter the data. Default is NULL.
#' @return A plot object created with the filtered data by the pathfindR enrichment_chart() method
#' @import dplyr
#' @import ggplot2
#' @import pathfindR
#' @import purrr
#' @examples
#' # Example usage:
#' # enricher(data, clusters = c(1), genes = c("Gene1"), pathways = c("Pathway A"))
#' @export
enricher <- function(

    data = NULL,
    clusters = NULL,
    genes = NULL,
    pathways = NULL

    ){

  #______________INPUT VALIDATION_____________
  #----

  if( is.null(data) ){
    stop("There was no data input")
  }

  #Ensure required format is met
  expected_names <- c("ID", "Term_Description", "Fold_Enrichment", "occurrence", "support",
                      "lowest_p", "highest_p", "non_Signif_Snw_Genes", "Up_regulated",
                      "Down_regulated", "all_pathway_genes", "num_genes_in_path", "Cluster", "Status")

  if( length(intersect(expected_names, colnames(data))) < length(expected_names)) {
    stop("The data is not the correct format")
  }

  #Preset for search conditions not used
  if( is.null(clusters) ){
    bycluster <- data %>% filter(ID == "NULL VALUE")
  }
  if( is.null(genes) ){
    bygene <- data %>% filter(ID == "NULL VALUE")
  }
  if( is.null(pathways) ){
    bypath <- data %>% filter(ID == "NULL VALUE")
  }
  #----

  #______________DATA MANIPULATION____________
  #----

  #Change the all pathway gene lists generated by pathfindR to a list of individual gene names
  data <- data %>%
    mutate(gene_list = lapply(all_pathway_genes, function(x) trimws(unlist(strsplit(x, ",")))))

  #Create separate dfs with hits for each search criteria

  #CLUSTERS
  if( ! is.null(clusters) ){
    clusters <- clusters %>% as.numeric()
    bycluster <- data %>% filter( Cluster %in% clusters)
  }
  #GENES
  if( ! is.null(genes) ){
    bygene <- data %>%
      filter(map_lgl(gene_list, ~ any(.x %in% genes)))
  }
  #PATHWAYS
  if( ! is.null(pathways) ){
    bypath <- data %>%
      filter(Term_Description %in% pathways)
  }

  #Remake larger data frame with all hits distinctively
  hits <- rbind(bycluster, bygene, bypath) %>% distinct()

  #Default for no hits
  if( nrow(hits) < 1){
    #Show the first 10 clusters
    hits <- subset(data, Cluster %in% 1:10)
  }

  #----

  #______________CREATE THE PLOT______________
  plot <- enrichment_chart(hits, plot_by_cluster = TRUE)

  return(plot)

}
